### ISSUE TITLE
module segfaults for high spike rates

### ISSUE THREAD

**Issue by awillats** [awillats/hmm-generator#1]
#### RTXI Version:
RTXI version 2.2 on Ubuntu 16.04 running in a virtual machine in virtualbox

#### Description: 
load in hmm-generator, set one of the rates to ~30 or larger, and eventually rtxi will freeze. 
This doesn't seem to happen for lower values, but is probabilistic, so may just be less likely.

#### Error Message: 
```
Thread 4 "RTXI RT Thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe48e6700 (LWP 2850)]
0x00007fffd5816786 in viterbi(HMMv const&, std::vector<int, std::allocator<int> >, int) ()
   from /usr/local/lib/rtxi/hmm_generator.so

[gdb backtrace]

#0  0x00007fffd5816786 in viterbi(HMMv const&, std::vector<int, std::allocator<int> >, int) ()
   from /usr/local/lib/rtxi/hmm_generator.so
#1  0x00007fffd58126ac in HmmGenerator::decodeHMM(HMMv) () from /usr/local/lib/rtxi/hmm_generator.so
#2  0x00007fffd5812d1e in HmmGenerator::decodeSpkBuffer() () from /usr/local/lib/rtxi/hmm_generator.so
#3  0x00007fffd5813b25 in HmmGenerator::restartHMM() () from /usr/local/lib/rtxi/hmm_generator.so
#4  0x00007fffd5813edd in HmmGenerator::stepHMM() () from /usr/local/lib/rtxi/hmm_generator.so
#5  0x000000000042cb09 in RT::System::execute() ()
#6  0x000000000042cc5e in RT::System::bounce(void*) ()
#7  0x00007ffff5183d8a in task_entry () from /usr/xenomai/lib/libalchemy.so.0
#8  0x00007ffff4f7020b in thread_trampoline () from /usr/xenomai/lib/libcopperplate.so.0
#9  0x00007ffff4d58aec in cobalt_thread_trampoline () from /usr/xenomai/lib/libcobalt.so.2
#10 0x00007ffff492e6ba in start_thread (arg=0x7fffe48e6700) at pthread_create.c:333
#11 0x00007ffff3bbb3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by awillats** [comment]
segfault seems to have disappear for now, was also an associated memory leak which has probably been closed!
